### ISSUE TITLE
unrecognized subcommand 'toggle-pane-zoom-state'

### ISSUE THREAD

**Issue by uc-advocate** [quantonganh/helix-wezterm#1]
Hi!

 i am getting %subj% error message - seems like my version of Wezterm doesn't recognize the  'toggle-pane-zoom-state' subcommand.

What am i doing wrong? I've got the latest version of Wezterm from git and compiled it.

Thanks

**Comment by quantonganh** [comment]
Could you please try [this](https://github.com/quantonganh/helix-wezterm/commit/f46e799518544ede4c20b78c848e3c9a80ee2ebb)?

**Comment by uc-advocate** [comment]
> Could you please try [this](https://github.com/quantonganh/helix-wezterm/commit/f46e799518544ede4c20b78c848e3c9a80ee2ebb)?

This is it! Now it works.
Thank you!
