### ISSUE TITLE
File not opening in helix when using the explorer

### ISSUE THREAD

**Issue by andreatitolo** [quantonganh/helix-wezterm#10]
Hi! thanks for all this work :) I am not a developer so my use case is very limited compared to the possibilities this configuration offers, but I still enjoy working with Helix, Wezterm, and Lazygit.

I am encountering a problem when using the `explorer` however: I followed [these suggestions](https://github.com/quantonganh/blog/issues/37#issuecomment-1701271382) from your blog post to configure broot and create the `hx-open.sh` file. 

However, when I am selecting a file from broot and opening with `enter`, the path of the file is indeed sent to the right pane, but copied in the bottom bar of helix as: `global-search:path/to/filej`(I don't know why the 'j' is added at the end tough), and hitting enter again open the helix file picker but with empty results.

I am clearly missing something for my lack of knowledge, so apologies if this sound like a stupid question.
The hx-open.sh script is the following:

```sh
#!/usr/bin/env sh

fpath="$1"

pane_id=$(wezterm cli get-pane-direction right)
if [ -z "${pane_id}" ]; then
  pane_id=$(wezterm cli split-pane --right --percent 80)
fi

program=$(wezterm cli list | awk -v pane_id="$pane_id" '$3==pane_id { print $6 }')
if [ "$program" = "hx" ]; then
  echo ":open ${fpath}\r" | wezterm cli send-text --pane-id $pane_id --no-paste
else
  echo "hx ${fpath}" | wezterm cli send-text --pane-id $pane_id --no-paste
fi

wezterm cli activate-pane-direction --pane-id $pane_id right

```

Thanks in advance and thanks again for putting all this together!

**Comment by quantonganh** [comment]
Hi,

Thank you for your words. It's always a joy to know that someone is still using something I wrote for myself.

Since the global search is triggered by pressing `space`, followed by `/`, I cannot think of the reason why `echo ":open /path/to/file\r"` is interpreted as `echo " /path/to/file"` (with a leading space, and no `\r`), then becomes `global-search:path/to/filej`. Can you reproduce this issue consistently?

**Comment by andreatitolo** [comment]
Thanks for you answer :) yes unfortunately every time I try it to open a file I get this result. 

While I was doing some tests, one thing that changed is if helix is already opened or not. Basically if the process is:
Single pane Wezterm -> open broot -> select file and open, wezterm creates a new pane on the right with helix and the file opened.

However if helix is already opened, I get the issue with the `echo ":open ` being interpreted as `global-search:`. Of course the file that is already opened stays there (but the line where the cursor is gets selected for some reasons)

**Comment by quantonganh** [comment]
@andreatitolo I think I've found something.

How did you launch helix? Did you use `hx` or the full path (e.g., `/opt/homebrew/bin/hx`)? I suspect you're using the later. The command I used to get the program is:

```sh
wezterm cli list | awk -v pane_id="$pane_id" '$3==pane_id { print $6 }'
```

This returns that full path `/opt/homebrew/bin/hx`. Since this differs from `hx`, it falls into the else branch:

```sh
echo "hx ${fpath}" | wezterm cli send-text --pane-id $pane_id --no-paste
```

`h`: move the cursor to the left
`x`: delete
` /path/to/file`: `space`, follow by `/` opens global search, then pastes `path/to/file`.

This is why you got `global-search:path/to/filej`. I'm not sure why `j` is appended at the end, but I suspect it is caused by `\r` and `--no-paste`.

Anyway, could you please update `hx-open.sh` as shown [here](https://github.com/quantonganh/dotfiles/commit/b93ae6b16f0856f64ec2094f1c002462df78378d), and try again?

**Comment by andreatitolo** [comment]
@quantonganh thanks for the anwer :)
I was using `hx` but the binary is in `/opt/homebrew/bin/hx`. I can confirm that is the issue happening, the program is not retrieved so it always falls in the else branch. 

I tried with the new `hx-open.sh` but unfortunately I get the same issue. It seems that the output that is passed to the wezterm cli is always the pane path and not the pane title/program.

If I explictly declare the wezterm pane_id and try 
```
wezterm cli list --format json | jq --arg pane_id 1 -r '.[] | select(.pane_id  == (1 | tonumber)) | .title'
```

I get the pane path even when helix is opened. Trying to use also the full path `/opt/homebrew/bin/hx` in the if statement didn't work. 
Could it be some wezterm configuration I am missing? I saw the docs on `get_foreground_process()` but I am not sure using that in the config can be useful.

Really sorry to bother you with this, I understand this is a personal project and I don't want to put too much pressure :)

**Comment by quantonganh** [comment]
Make sure that you're using [fish shell](https://fishshell.com/), so you can see `hx` in the pane title when listing panes:

```sh
  {
    "window_id": 0,
    "tab_id": 149,
    "pane_id": 326,
    "workspace": "default",
    "size": {
      "rows": 23,
      "cols": 175,
      "pixel_width": 2975,
      "pixel_height": 851,
      "dpi": 144
    },
    "title": "hx . ~/C/p/helix-wezterm",
    ...
```

**Comment by andreatitolo** [comment]
I was using it as interactive shell, but even making it login shell I get the following (pane_id 1 has helix opened using `hx`)

```
  {
    "window_id": 0,
    "tab_id": 0,
    "pane_id": 1,
    "workspace": "default",
    "size": {
      "rows": 50,
      "cols": 95,
      "pixel_width": 855,
      "pixel_height": 900,
      "dpi": 72
    },
    "title": "~/.c/broot",
    ...
```

I was searching around but not much I can find on this specific issue with fish+wezterm and pane title

**Comment by quantonganh** [comment]
Do you use the default [fish_title](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_title.fish) or a custom version?

**Comment by andreatitolo** [comment]
That was it, I did not have a `fish_title.fish` in my `functions`folder. 
Now after a quick test everything seems to work perfectly, thank you so much for your help :)
