### ISSUE TITLE
Help on Usage

### ISSUE THREAD

**Issue by Rope-a-dope** [quantonganh/helix-wezterm#12]
Thank you so much such a wonderful blog and tool. I followed everything except the first part of usage because I don't know what to do. I already have [fish_title](https://fishshell.com/docs/current/cmds/fish_title.html) [function](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_title.fish).  What else to do? The code below doesn't look like config for WezTerm.
```
  {
    "window_id": 0,
    "tab_id": 167,
    "pane_id": 350,
    "workspace": "default",
    "size": {
      "rows": 48,
      "cols": 175,
      "pixel_width": 2975,
      "pixel_height": 1776,
      "dpi": 144
    },
    "title": "hx . ~/C/p/helix-wezterm",
```
~/.config/fish/config.fish
```
function fish_title
    # If we're connected via ssh, we print the hostname.
    set -l ssh
    set -q SSH_TTY
    and set ssh "["(prompt_hostname | string sub -l 10 | string collect)"]"
    # An override for the current command is passed as the first parameter.
    # This is used by `fg` to show the true process name, among others.
    if set -q argv[1]
        echo -- $ssh (string sub -l 20 -- $argv[1]) (prompt_pwd -d 1 -D 1)
    else
        # Don't print "fish" because it's redundant
        set -l command (status current-command)
        if test "$command" = fish
            set command
        end
        echo -- $ssh (string sub -l 20 -- $command) (prompt_pwd -d 1 -D 1)
    end
end
```

**Comment by quantonganh** [comment]
Sorry for not making it clear. I've just pushed [a fix](https://github.com/quantonganh/helix-wezterm/commit/e81df037e0e800dba3d007c5d8a6e0330dd6a434) to clarify.

**Comment by Rope-a-dope** [comment]
> Sorry for not making it clear. I've just pushed [a fix](https://github.com/quantonganh/helix-wezterm/commit/e81df037e0e800dba3d007c5d8a6e0330dd6a434) to clarify.

Thank you so much! Works great!
