### ISSUE TITLE
Rebinds "collapse selection" keybinding without recommending an alternative

### ISSUE THREAD

**Issue by markstos** [quantonganh/helix-wezterm#4]
The Usage section recommends rebinding the ";" key in normal mode, but it has a default binding: To collapse the selection. 

It would be good to mention the side-effect of the recommending keybindings and mention an alternate keybinding to use for collapse selection or how you avoid needing it.

**Comment by markstos** [comment]
Here's some suggestions for non-conflicting bindings. While most of the base keymap is already taken with default bindings, there are some free spots within the "space" menu, so that "space comma" or "space semicolon" can be a two-character leader. Here's an example of using "space comma" as the leader:

```
[keys.normal.space.","]
```

**Comment by quantonganh** [comment]
Sounds like I merged it too fast.

> The Usage section recommends rebinding the ";" key in normal mode, but it has a default binding: To collapse the selection.

By default, `;` is only bound in the select mode, no?

**Comment by markstos** [comment]
I tested, and you are correct. Re-binding ";" in normal mode does not appear to impact the use of ";" in "select" mode.

**Comment by markstos** [comment]
To reverse again: I heard from a maintainer, who in turn pointed to the source code to confirm that in fact, ";" *is* also bound in normal mode to collapse_selection, so it's not a good leader key choice. 

https://github.com/helix-editor/helix/discussions/7822#discussioncomment-9766391
