### ISSUE TITLE
hx-fzf.sh vs helix-fzf.sh

### ISSUE THREAD

**Issue by markstos** [quantonganh/helix-wezterm#7]
helix-wezterm.sh references `hx-fzf.sh`, but the name actually distributed is `helix-fzf.sh`. Those should match.

**Comment by quantonganh** [comment]
It has been [corrected](https://github.com/quantonganh/helix-wezterm/commit/3753a5b5fc682b04a2b9a96806542a7abfb14bd9), thanks.
